### PR TITLE
Multiple updates to make the plugin compliant to the latest leaflet

### PR DESCRIPTION
**Pull request by SergioGutTal**

### CODE REVIEW

**Comment by danzel** [comment]
Thanks.
We can drop the IE6 ajax support too if you want to do that?

Leaflet is IE7+ now.

**Comment by SergioGutTal** [comment]
Not a strong opinion about that...

**Comment by danzel** [comment]
Ok, bringing it in.

**Comment by danzel** [comment]
We probably need to update the examples? If you could do that too <3

**Pull request merged**
