### PR TITLE
some modernization

### PR DESCRIPTION
**Pull request by calvinmetcalf**
does 2 things in 2 commits, and I can revert the 2nd one if need be

1. removes the legacy support for browsers that don't support XHR and JSON.parse, on the grounds that leaflet doesn't actually support.  It was probably unnecessary when it was put in (by me) and all it will likely do is cause security errors.   This should also handle errors due to cors issues better now (they have status of 0).
2. added a package.json for dependency management, I.E. to run the build without having to globally install jake, uglify and jshint, this also fixes the uglify-js code to work with the more recent version and changes the examples to point the the dist folder and to use the most recent leaflet code to enable me to test change 1.  This change can be reverted.

### CODE REVIEW

**Comment by danzel** [comment]
Sounds good, github is telling me there are merge issues, fix those and we'll bring this in :)

**Comment by calvinmetcalf** [comment]
fixed

**Comment by danzel** [comment]
Cool, trusting this works :)

**Comment by calvinmetcalf** [comment]
so that was one reason for some of the extra changes, so I could actually check that it worked

**Pull request merged**
